import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FileText, ShieldCheck, ImagePlus } from 'lucide-react';
import Navbar from '../components/Navbar'; import Footer from '../components/Footer'; import api from '../services/api'; import { useToast } from '../context/ToastContext';
const CATEGORIES=['Smartphone','Laptop','Smartwatch','Watch','Earphones','ID Card','Wallet','Keys','Bag','Books','Documents','Accessories','Clothing','Other'];
const input='w-full px-4 py-2.5 bg-gray-50 border border-gray-300 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-blue-500';
export default function CreateMissingPage(){
 const state=useLocation().state?.aiSearchState||{}, navigate=useNavigate(), {showToast}=useToast();
 const [form,setForm]=useState({itemName:state.itemName||'',category:CATEGORIES.includes(state.category)?state.category:'Smartphone',brand:state.brand||'',color:state.color||'',publicDescription:state.description||'',lastKnownLocation:state.location||'',approximateLostDate:/^\d{4}-/.test(state.date||'')?state.date:new Date().toISOString().slice(0,10),approximateLostTime:'',privateVerificationDetails:''});
 const [image,setImage]=useState(null),[loading,setLoading]=useState(false); const set=(k,v)=>setForm({...form,[k]:v});
 async function submit(e){e.preventDefault();setLoading(true);try{const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,v));if(image)data.append('image',image);const r=await api.post('/missing',data);showToast(r.data.message,'success');navigate('/my-posts');}catch(err){showToast(err.response?.data?.message||'Could not post missing item.','error');}finally{setLoading(false)}}
 return <div className="min-h-screen flex flex-col bg-gray-50"><Navbar/><main className="flex-1 max-w-3xl w-full mx-auto px-4 py-10"><h1 className="text-3xl font-extrabold text-gray-900">Report Missing Item</h1><p className="text-sm text-gray-500 mt-1 mb-7">LostLink will keep checking current and future found posts.</p>
 <form onSubmit={submit} className="bg-white p-6 sm:p-8 rounded-3xl border shadow-sm space-y-7">
 <section><h2 className="font-extrabold text-gray-900 mb-1">Public information</h2><p className="text-xs text-gray-500 mb-4">Shown to students who may have seen your item.</p><div className="grid sm:grid-cols-2 gap-4">
 <label className="sm:col-span-2 border-2 border-dashed rounded-2xl p-4 text-sm text-gray-600 flex gap-2 items-center cursor-pointer"><ImagePlus className="w-5 h-5"/>{image?image.name:'Optional item image'}<input type="file" accept="image/*" className="hidden" onChange={e=>setImage(e.target.files[0])}/></label>
 {[['itemName','Item name *'],['brand','Brand'],['color','Color *'],['lastKnownLocation','Last known location *']].map(([k,l])=><label key={k} className="text-xs font-bold text-gray-700">{l}<input className={`${input} mt-1`} required={l.includes('*')} value={form[k]} onChange={e=>set(k,e.target.value)}/></label>)}
 <label className="text-xs font-bold text-gray-700">Category *<select className={`${input} mt-1`} value={form.category} onChange={e=>set('category',e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="text-xs font-bold text-gray-700">Approximate date lost *<input type="date" required className={`${input} mt-1`} value={form.approximateLostDate} onChange={e=>set('approximateLostDate',e.target.value)}/></label>
 <label className="text-xs font-bold text-gray-700">Approximate time (optional)<input type="time" className={`${input} mt-1`} value={form.approximateLostTime} onChange={e=>set('approximateLostTime',e.target.value)}/></label>
 <label className="sm:col-span-2 text-xs font-bold text-gray-700">Public description *<textarea required rows="3" className={`${input} mt-1`} value={form.publicDescription} onChange={e=>set('publicDescription',e.target.value)} placeholder="General appearance and circumstances; do not include secrets."/></label></div></section>
 <section className="rounded-2xl bg-blue-50 border border-blue-200 p-5"><h2 className="font-extrabold text-blue-950 flex gap-2"><ShieldCheck className="w-5 h-5"/>Private verification information</h2><p className="text-xs text-blue-700 my-2">Private details are never shown publicly. They are used only to verify someone who says they found your item.</p><textarea rows="4" className={input} value={form.privateVerificationDetails} onChange={e=>set('privateVerificationDetails',e.target.value)} placeholder="Unique sticker, crack location, wallpaper, engraving, case, initials, serial fragment..."/></section>
 <button disabled={loading} className="w-full py-4 rounded-2xl bg-blue-600 text-white font-bold flex justify-center gap-2 disabled:opacity-50"><FileText className="w-5 h-5"/>{loading?'Publishing...':'Publish Missing Item Request'}</button></form></main><Footer/></div>;
}
