import React,{useEffect,useState} from 'react'; import {useNavigate,useParams} from 'react-router-dom'; import Navbar from '../components/Navbar'; import Footer from '../components/Footer'; import api from '../services/api'; import {useAuth} from '../context/AuthContext'; import {useToast} from '../context/ToastContext';
const field='w-full border border-gray-300 rounded-xl px-3 py-2 text-sm';
export default function MissingDetailPage(){const {id}=useParams(),nav=useNavigate(),{user}=useAuth(),{showToast}=useToast();const [item,setItem]=useState(null),[evidence,setEvidence]=useState([]),[file,setFile]=useState(null),[form,setForm]=useState({foundLocation:'',foundDate:new Date().toISOString().slice(0,10),foundTime:'',category:'',brand:'',color:'',description:'',verificationAnswers:''});const set=(k,v)=>setForm({...form,[k]:v});const owner=item&&(item.userId===user?._id||item.userId?._id===user?._id);
 async function load(){const m=(await api.get(`/missing/${id}`)).data;setItem(m);if(m.userId===user?._id||m.userId?._id===user?._id)setEvidence((await api.get(`/missing/${id}/found-evidence`)).data||[])} useEffect(()=>{load()},[id,user?._id]);
 async function submit(e){e.preventDefault();try{const d=new FormData();Object.entries(form).forEach(([k,v])=>d.append(k,v));if(file)d.append('image',file);const r=await api.post(`/missing/${id}/found-evidence`,d);showToast(r.data.message,'success');nav('/my-posts');}catch(err){showToast(err.response?.data?.message||'Could not submit evidence.','error')}}
 async function decide(eid,action){try{const r=await api.post(`/missing/${id}/found-evidence/${eid}/${action}`);showToast(r.data.message,'success');load();if(r.data.conversationId)nav('/messages')}catch(err){showToast(err.response?.data?.message||'Could not review evidence.','error')}}
 if(!item)return <div className="p-10">Loading...</div>;return <div className="min-h-screen flex flex-col bg-gray-50"><Navbar/><main className="flex-1 max-w-4xl w-full mx-auto px-4 py-9"><div className="bg-white border rounded-3xl p-6 mb-6"><span className="text-xs font-black text-rose-600">MISSING · {item.status}</span><h1 className="text-3xl font-extrabold mt-2">{item.itemName}</h1><p className="text-sm text-gray-600 mt-2">{item.brand} · {item.color} · {item.category}</p><p className="mt-4">{item.description}</p><p className="text-sm mt-3">Last seen at <b>{item.lastKnownLocation}</b> on {new Date(item.approximateLostDate).toLocaleDateString()}</p></div>
 {owner?<section><h2 className="text-xl font-extrabold mb-3">Review Found Evidence</h2>{evidence.length===0?<div className="bg-white p-8 rounded-2xl text-gray-500">No finder responses yet.</div>:evidence.map(e=><article key={e._id} className="bg-white border rounded-2xl p-5 mb-4"><div className="flex justify-between"><b>{e.finderId?.name?.split(' ')[0]||'Student'}</b><span className="font-black text-blue-700">{e.matchScore}% {e.confidence} MATCH</span></div>{e.evidenceImageUrl&&<img src={e.evidenceImageUrl} className="mt-3 w-56 h-44 object-cover rounded-xl"/>}<p className="text-sm mt-3"><b>Found:</b> {e.foundLocation} · {e.brand} {e.color}</p><p className="text-sm mt-2">{e.description}</p><p className="text-xs text-gray-500 mt-2">{e.matchReasons?.join(' · ')}</p>{e.status==='PENDING_REVIEW'?<div className="flex gap-2 mt-4"><button onClick={()=>decide(e._id,'accept')} className="bg-emerald-600 text-white px-4 py-2 rounded-xl font-bold">Accept & Chat</button><button onClick={()=>decide(e._id,'reject')} className="bg-red-50 text-red-700 px-4 py-2 rounded-xl font-bold">Reject</button></div>:<b className="block mt-3">{e.status}</b>}</article>)}</section>:
 <form onSubmit={submit} className="bg-white border rounded-3xl p-6 space-y-4"><h2 className="text-xl font-extrabold">Did you find this item?</h2><p className="text-sm text-gray-500">Help us verify that the item you found matches this missing report. Chat stays locked until the owner accepts.</p><label className="block border-2 border-dashed rounded-xl p-4 text-sm">Upload a photo (optional)<input type="file" accept="image/*" className="block mt-2" onChange={e=>setFile(e.target.files[0])}/></label><div className="grid sm:grid-cols-2 gap-3">{[['foundLocation','Where did you find it?'],['foundDate','When did you find it?'],['category','Item category'],['brand','Brand/model'],['color','Color']].map(([k,l])=><label key={k} className="text-xs font-bold">{l}<input type={k==='foundDate'?'date':'text'} className={`${field} mt-1`} value={form[k]} onChange={e=>set(k,e.target.value)}/></label>)}<label className="sm:col-span-2 text-xs font-bold">Describe the item<textarea className={`${field} mt-1`} rows="3" value={form.description} onChange={e=>set('description',e.target.value)}/></label><label className="sm:col-span-2 text-xs font-bold">Independent identifying details<textarea className={`${field} mt-1`} rows="3" value={form.verificationAnswers} onChange={e=>set('verificationAnswers',e.target.value)} placeholder="Sticker/design, case, visible damage, accessory/keychain, unusual marks..."/></label></div><p className="text-xs text-amber-700">The owner's private answers are never shown to you.</p><button className="w-full bg-blue-600 text-white rounded-xl py-3 font-bold">Submit Evidence for Owner Review</button></form>}
 </main><Footer/></div>}
